# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rabidaudio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: cheap-static-sites
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cheap-static-sites

stages:
  default:
    params:
      tablePrefix: "${self:org}-${self:app}-${sls:stage}"

provider:
  name: aws
  runtime: nodejs22.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [SitesTable, Arn]
            - Fn::GetAtt: [DeploymentsTable, Arn]
        - Effect: Allow
          Action:
            - s3:GetObjectAcl
            - s3:GetObject
            - s3:GetObjectAttributes
            - s3:GetObjectVersionAcl
            - s3:GetObjectTagging
            - s3:PutObject
            - s3:DeleteObject
            - s3:GetBucketAcl
            - s3:AbortMultipartUpload
            - s3:ListBucket
          Resource:
            - Fn::GetAtt: [DeploymentBucket, Arn]
            - Fn::Join:
              - ''
              - - Fn::GetAtt: [DeploymentBucket, Arn]
                - '/*'
  environment:
    TABLE_PREFIX: ${param:tablePrefix}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    DeploymentBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${param:tablePrefix}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-users
    SitesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: siteId
            AttributeType: S
        KeySchema:
          - AttributeName: siteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-sites
    DeploymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: siteId
            AttributeType: S
          - AttributeName: deploymentId
            AttributeType: S
        KeySchema:
          - AttributeName: siteId
            KeyType: HASH
          - AttributeName: deploymentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-deployments
