org: rabidaudio
app: static-chic
service: static-chic

stages:
  default:
    params:
      # A hosted zone for param:baseDomain.
      # Because the same hostedzone is used for all envrionments,
      # it has to be created outside of this CF template and it's
      # ID needs to be put here.
      hostedZoneId: Z0815807GYU44VR2QYOU
      baseDomain: static-chic.online
      appId: ${self:app}-${sls:stage}
      bucketName: ${param:appId}
      tablePrefix: ${param:appId}
      apiDomain: api.${sls:stage}.${param:baseDomain}
      sitesDomain: sites.${sls:stage}.${param:baseDomain}
  prod:
    params:
      apiDomain: api.${param:baseDomain}
      sitesDomain: sites.${param:baseDomain}

provider:
  name: aws
  runtime: nodejs22.x
  domain: ${param:apiDomain}
  stackTags:
    app: ${self:app}
    stage: ${sls:stage}
  ecr:
    images:
      # NOTE: docker with buildx needs to be installed locally
      appimg:
        path: .
        platform: linux/amd64
        provenance: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [AuthRequestsTable, Arn]
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [SitesTable, Arn]
            - Fn::Join:
              - ''
              - - Fn::GetAtt: [SitesTable, Arn]
                - "/index/*"
            - Fn::GetAtt: [DeploymentsTable, Arn]
        - Effect: Allow
          Action:
            - s3:GetObjectAcl
            - s3:GetObject
            - s3:GetObjectAttributes
            - s3:GetObjectVersionAcl
            - s3:GetObjectTagging
            - s3:PutObject
            - s3:DeleteObject
            - s3:GetBucketAcl
            - s3:AbortMultipartUpload
            - s3:ListBucket
          Resource:
            - Fn::GetAtt: [DeploymentBucket, Arn]
            - Fn::Join:
              - ''
              - - Fn::GetAtt: [DeploymentBucket, Arn]
                - '/*'
        - Effect: Allow
          Action:
            # These have no resource
            - cloudfront:ListDistributionTenants
            - cloudfront:CreateDistributionTenant
            # These have a resource of the tenant ARN which we can't set dynamically
            - cloudfront:GetDistributionTenant
            - cloudfront:ListInvalidationsForDistributionTenant
            - cloudfront:GetDistributionTenantByDomain
            - cloudfront:DeleteDistributionTenant
            - cloudfront:CreateInvalidationForDistributionTenant
            - cloudfront:GetInvalidationForDistributionTenant
            - cloudfront:UpdateDistributionTenant
          Resource: "*"
        - Effect: Allow
          Action:
            - route53:ChangeResourceRecordSets
          Resource: arn:aws:route53:::hostedzone/${param:hostedZoneId}

  environment:
    NODE_ENV: ${sls:stage}
    HOSTNAME: ${param:apiDomain}
    APP_NAME: ${self:app}
    STAGE: ${sls:stage}
    APP_ID: ${param:appId}
    SITES_DOMAIN: ${param:sitesDomain}
    HOSTED_ZONE_ID: ${param:hostedZoneId}
    DISTRIBUTION_ID: !Ref CloudfrontDistro
    CONNECTION_GROUP_ID: !GetAtt CloudfrontDistroDefaultConnectionGroup.Id
    DISTRIBUTION_DOMAIN: !GetAtt CloudfrontDistroDefaultConnectionGroup.RoutingEndpoint
    TABLE_PREFIX: ${param:tablePrefix}
    BUCKET_NAME: ${param:bucketName}

functions:
  api:
    # NOTE: switching between docker and native handler causes the whole stack to turn over.
    # perhaps we can delete just the function?
    # handler: handler.handler
    image:
      name: appimg
    events:
      - httpApi: "*"

resources:
  Resources:
    # DynamoDB Tables
    AuthRequestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: authReqId
            AttributeType: S
        KeySchema:
          - AttributeName: authReqId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-auth-requests
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-users
    SitesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: siteId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: siteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-sites
        GlobalSecondaryIndexes:
          - IndexName: idxUserId
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    DeploymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: siteId
            AttributeType: S
          - AttributeName: deploymentId
            AttributeType: S
        KeySchema:
          - AttributeName: siteId
            KeyType: HASH
          - AttributeName: deploymentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tablePrefix}-deployments
    # S3 Bucket 
    DeploymentBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${param:bucketName}
    # A policy that allows AccessIdentity to read the contents of DeploymentBucket
    # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: DeploymentBucket
        PolicyDocument:
          Version: "2012-10-17"
          Id: PolicyForCloudFrontPrivateContent
          Statement:
            - Sid: AllowCloudFrontServicePrincipal
              Effect: Allow
              Principal:
                Service: cloudfront.amazonaws.com
              Action: s3:GetObject
              Resource:
                - Fn::Join:
                  - '/'
                  - - Fn::GetAtt: [DeploymentBucket, Arn]
                    - "sites"
                    - "*"
              Condition:
                ArnLike:
                  AWS:SourceArn:
                    - Fn::Join:
                      - '/'
                      - - "arn:aws:cloudfront::*:distribution"
                        - Ref: CloudfrontDistro
    # Access control to allow cloudfront to access data in the bucket
    OAC:
      Type: AWS::CloudFront::OriginAccessControl
      Properties: 
        OriginAccessControlConfig: 
            Name: ${param:tablePrefix}
            OriginAccessControlOriginType: s3
            SigningBehavior: always
            SigningProtocol: sigv4
    # A multi-tenant CloudFront distribution. Tenants will be added to it dynamically
    CloudfrontDistro:
      Type: AWS::CloudFront::Distribution
      Properties:
        Tags:
          - Key: Name
            Value: ${param:tablePrefix}
        DistributionConfig:
          ConnectionMode: tenant-only
          DefaultRootObject: "index.html"
          HttpVersion: http2and3
          Enabled: true
          DefaultCacheBehavior:
            TargetOriginId:
              Fn::GetAtt: [DeploymentBucket, Arn]
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            # "CachingOptimized" default cache policy, recommended for S3
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TenantConfig: 
            ParameterDefinitions:
              - Name: siteId
                Definition:
                  StringSchema:
                    Comment: "Site ID"
                    DefaultValue: "root"
                    Required: false
          Origins:
            - DomainName:
                Fn::GetAtt: [DeploymentBucket, RegionalDomainName]
              Id:
                Fn::GetAtt: [DeploymentBucket, Arn]
              OriginAccessControlId:
                Ref: OAC
              S3OriginConfig:
                OriginAccessIdentity: ""
              OriginPath: '/sites/{{siteId}}/content'
          ViewerCertificate:
            AcmCertificateArn:
              Ref: SiteCertificate
            MinimumProtocolVersion: TLSv1.2_2021
            SslSupportMethod: sni-only
    # AWS can create a default connection group, but we need
    # to make one to reference the domain
    CloudfrontDistroDefaultConnectionGroup:
      Type: AWS::CloudFront::ConnectionGroup
      Properties:
        Enabled: true
        Ipv6Enabled: true
        Name: ${param:tablePrefix}-default
    SiteDomain:
      Type: AWS::Route53::RecordSet
      Properties: 
        HostedZoneId: ${param:hostedZoneId}
        Name: ${param:sitesDomain}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # A special HostedZone for CF
          EvaluateTargetHealth: false
          DNSName:
            Fn::GetAtt: [CloudfrontDistroDefaultConnectionGroup, RoutingEndpoint]
    # A default certificate to use for sites
    SiteCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: ${param:sitesDomain}
        SubjectAlternativeNames:
          - "*.${param:sitesDomain}"
        ValidationMethod: DNS
        DomainValidationOptions:
          - DomainName: ${param:sitesDomain}
            HostedZoneId: ${param:hostedZoneId}
